### ISSUE TITLE
fix token icons to match mobile

### ISSUE THREAD

**Issue by paOol** [Bitcoin-com/badger#170]
Match icon images with badger mobile.

**Comment by SpicyPete** [comment]
Also effects addresses I believe.
Issue is caused since all blockies in the extension have their first `n` characters to remove.
So for an address like `bitcoincash:32hdjsgfsahfdj`, the block is generated for `32hdjsgfsahfdj`.

The problem is, we want the full tokenID used for the blockie, not just the truncated version.
Ping me for more info if needed.
